<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Attendance Sheet — {{ $event->title }}</title>
    <style>
        /* Repeating header/footer: the real PDF is generated by an external Puppeteer
           (headless Chrome) service — see chrome-print-server.js — which has its own
           native "headerTemplate"/"footerTemplate" mechanism (built and passed in by
           FestReportService::attendanceSheetPdf()) that Chromium repeats on every
           printed page, isolated from this page's own content. That's what actually
           renders the branding/page-numbers in production, so this stylesheet doesn't
           need a CSS-based repeating header/footer for that path at all.
           dompdf (used only when PDF_CONVERTER_URL isn't configured, e.g. local dev)
           has no equivalent native mechanism, so it still gets a branding row baked
           into each item table's <thead>/<tfoot> — the one repeat-per-page trick that
           reliably works there (dompdf reprints thead/tfoot on every page a table
           spans, which is also why the SL/Chest No/... column header repeats).
           The on-screen preview has no concept of pages at all, so it keeps a simple
           normal-flow header/footer shown once at the top/bottom. */
        @page {
            margin: 24px 38px;
        }
        body {
            font-family: 'DejaVu Sans', Arial, sans-serif;
            font-size: 10px;
            color: #0f172a;
            margin: 0;
            padding: 0;
        }
        .report-header {
            border-bottom: 2px solid #0f172a;
            padding-bottom: 6px;
            margin-bottom: 12px;
        }
        .event-context-bar {
            display: table;
            width: 100%;
            font-size: 9px;
            color: #334155;
            margin-top: 2px;
        }
        .event-context-bar .event-name {
            font-weight: bold;
            color: #0f172a;
        }
        .event-context-bar .sep {
            color: #94a3b8;
            padding: 0 4px;
        }
        .footer-container {
            display: table;
            width: 100%;
            border-top: 1px solid #cbd5e1;
            padding-top: 4px;
            margin-top: 16px;
            font-size: 8px;
            color: #64748b;
        }
        .footer-container .footer-left {
            display: table-cell;
            text-align: left;
            vertical-align: top;
        }
        .footer-container .footer-right {
            display: table-cell;
            text-align: right;
            white-space: nowrap;
            vertical-align: top;
        }
        main {
            width: 100%;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 0;
        }
        thead {
            display: table-header-group;
        }
        tfoot {
            display: table-footer-group;
        }
        th {
            background: #f1f5f9;
            color: #334155;
            font-size: 9px;
            font-weight: bold;
            text-transform: uppercase;
            letter-spacing: 0.04em;
            padding: 5px 6px;
            border: 1px solid #cbd5e1;
            text-align: left;
        }
        td {
            padding: 8px 7px;
            border: 1px solid #cbd5e1;
            font-size: 9px;
            color: #1e293b;
            vertical-align: middle;
        }
        tr:nth-child(even) td {
            background: #f8fafc;
        }
        .text-center {
            text-align: center;
        }
        .chest-no {
            font-weight: bold;
            color: #0f172a;
            font-size: 10px;
        }
        .school-name {
            text-transform: uppercase;
            color: #334155;
            font-size: 8px;
        }
        .team-divider td {
            background: #f1f5f9;
            color: #0f172a;
            font-weight: bold;
            font-size: 9px;
            padding: 4px 6px;
            border-top: 2px solid #cbd5e1;
            border-bottom: 1px solid #cbd5e1;
            text-transform: uppercase;
            letter-spacing: 0.03em;
        }
        .team-divider {
            page-break-inside: avoid;
        }
        .team-tag {
            display: inline-block;
            background: #dbeafe;
            color: #1e40af;
            font-size: 7px;
            font-weight: bold;
            padding: 1px 4px;
            border-radius: 3px;
            margin-top: 1px;
        }
        .photo-cell {
            width: 40px;
        }
        .photo-cell img {
            width: 36px;
            height: 36px;
            border-radius: 50%;
            object-fit: cover;
            border: 1px solid #e2e8f0;
        }
        .photo-cell .initials {
            width: 36px;
            height: 36px;
            border-radius: 50%;
            background: #e2e8f0;
            color: #64748b;
            font-size: 8px;
            font-weight: bold;
            display: inline-block;
            text-align: center;
            line-height: 36px;
        }
        .item-heading-bar {
            background: #0f172a;
            color: #ffffff;
            padding: 6px 10px;
            font-size: 11px;
            font-weight: bold;
            border-radius: 4px;
            text-transform: uppercase;
            letter-spacing: 0.03em;
            margin-bottom: 0;
            page-break-after: avoid;
        }
        .item-heading-bar .count-badge {
            float: right;
            background: #334155;
            color: #f8fafc;
            font-size: 9px;
            padding: 2px 8px;
            border-radius: 10px;
            font-weight: normal;
            text-transform: none;
            letter-spacing: normal;
        }
        .brand-row td, .foot-row td {
            border: none;
            padding: 0 0 6px;
        }
        .item-title-row td {
            border: none;
            padding: 4px 0 0;
            background: #ffffff;
        }
        .foot-row td {
            padding: 4px 0 0;
        }
        .brand-cell-table, .foot-cell-table {
            width: 100%;
            border-collapse: collapse;
        }
        .brand-cell-table td, .foot-cell-table td {
            border: none;
            padding: 0;
        }
        .brand-cell-table .logo-cell {
            width: 34px;
            vertical-align: middle;
            padding-right: 8px;
        }
        .brand-cell-table .logo-cell img {
            width: 28px;
            height: 28px;
            object-fit: contain;
        }
        .brand-cell-table .org-cell {
            vertical-align: middle;
        }
        .brand-cell-table .org-name {
            font-size: 12px;
            font-weight: 800;
            color: #0f172a;
            text-transform: uppercase;
        }
        .brand-cell-table .org-context {
            font-size: 8px;
            color: #475569;
            margin-top: 1px;
        }
        .brand-cell-table .doc-badge-cell {
            text-align: right;
            vertical-align: middle;
            white-space: nowrap;
        }
        .brand-cell-table .doc-badge {
            display: inline-block;
            background: #0f172a;
            color: #ffffff;
            padding: 3px 8px;
            border-radius: 3px;
            font-size: 8px;
            font-weight: bold;
            letter-spacing: 0.3px;
        }
        .foot-cell-table .foot-left {
            text-align: left;
            font-size: 7px;
            color: #64748b;
            border-top: 1px solid #cbd5e1;
            padding-top: 3px;
        }
        .foot-cell-table .foot-right {
            text-align: right;
            font-size: 7px;
            color: #64748b;
            white-space: nowrap;
            border-top: 1px solid #cbd5e1;
            padding-top: 3px;
        }
    </style>
</head>
<body>

@if(!empty($isPreview))
<div class="report-header">
    @include('partials.pdf-branding-header', [
        'orgName' => $sahodaya->name ?? 'SAHODAYA',
        'logoSrc' => $logo ?? null,
        'docTitle' => 'ATTENDANCE SHEET',
    ])
    <div class="event-context-bar">
        <span class="event-name">{{ $event->title }}</span>
        @if(!empty($singleItemName))
            <span class="sep">&bull;</span>
            <span>{{ $singleItemName }}</span>
        @endif
    </div>
</div>

<div class="footer-container">
    <span class="footer-left">{{ $sahodaya->name ?? 'SAHODAYA' }} &bull; {{ $event->title }} &bull; Generated {{ now()->format('d M Y, h:i A') }}</span>
    <span class="footer-right"></span>
</div>
@endif

<main>
@php
    // DomPDF is most reliable when each physical page is an explicit, standalone
    // table. Chunking prevents continuation pages from losing their organization,
    // event, item, and column headings when a long table crosses a page boundary.
    $reportSections = collect($rowsByItem)->flatMap(function ($itemRows, $itemName) use ($isPreview, $isDomPdf) {
        $allRows = collect($itemRows)->values();
        $chunks = empty($isPreview) && ($isDomPdf ?? true)
            ? $allRows->chunk(15)
            : collect([$allRows]);

        return $chunks->values()->map(fn ($chunk, $chunkIndex) => [
            'itemName' => $itemName,
            'rows' => $chunk->values()->all(),
            'allRows' => $allRows->all(),
            'offset' => $chunkIndex * 15,
        ]);
    })->values();
@endphp
@forelse($reportSections as $sectionIndex => $section)
    @php
        $itemName = $section['itemName'];
        $rows = $section['rows'];
        $allRows = $section['allRows'];
        $serialOffset = $section['offset'];
        $cleanTitle = str_replace('_', ' ', $itemName);
        $showDob = collect($rows)->contains(fn ($row) => !empty($row['_uses_age']));
        $showClass = !$showDob && collect($rows)->contains(fn ($row) => !empty($row['_uses_class']));
        $colspan = 6 + ($showDob || $showClass ? 1 : 0);

        // Team-based items (chess, quiz, group items, sports team events, etc.) group
        // several members under one chest/registration; count teams for those instead
        // of raw row count so the badge reads "56 Teams" rather than "223 Participants".
        $teamKeys = collect($allRows)->map(function ($r) {
            if (!empty($r['group_id'])) {
                return 'g_'.$r['group_id'];
            }
            if (!empty($r['team_name'])) {
                return 't_'.$r['team_name'].'_'.($r['school'] ?? '');
            }
            return null;
        })->filter()->unique();
        $teamCount = $teamKeys->count();
        $individualCount = collect($allRows)->filter(fn ($r) => empty($r['group_id']) && empty($r['team_name']))->count();

        if ($teamCount > 0 && $individualCount === 0) {
            $countLabel = $teamCount.' '.($teamCount === 1 ? 'Team' : 'Teams');
        } elseif ($teamCount > 0) {
            $countLabel = $teamCount.' '.($teamCount === 1 ? 'Team' : 'Teams').' &middot; '.count($allRows).' '.(count($allRows) === 1 ? 'Participant' : 'Participants');
        } else {
            $countLabel = count($allRows).' '.(count($allRows) === 1 ? 'Participant' : 'Participants');
        }
    @endphp
    <div style="margin-bottom: 18px; @if(empty($isPreview) && ($isDomPdf ?? true) && $sectionIndex > 0) page-break-before: always; @endif">
        @if(empty($isPreview) && ($isDomPdf ?? true))
        <div class="report-header">
            <table class="brand-cell-table">
                <tr>
                    @if(!empty($logo))
                        <td class="logo-cell"><img src="{{ $logo }}" alt=""></td>
                    @endif
                    <td class="org-cell">
                        <div class="org-name">{{ $sahodaya->name ?? 'SAHODAYA' }}</div>
                        <div class="org-context">{{ $event->title }}</div>
                    </td>
                    <td class="doc-badge-cell"><span class="doc-badge">ATTENDANCE SHEET</span></td>
                </tr>
            </table>
        </div>
        @endif
        @if(!empty($isPreview) || ($isDomPdf ?? true) || empty($singleItemName))
        <div class="item-heading-bar">
            {{ $cleanTitle }}
            <span class="count-badge">{!! $countLabel !!}</span>
        </div>
        @endif
        <table>
            <thead>
                <tr>
                    <th style="width: 28px;" class="text-center">Sl</th>
                    <th class="photo-cell"></th>
                    <th style="width: 55px;" class="text-center">Chest No</th>
                    <th>Participant / Team Name</th>
                    @if($showDob)
                        <th style="width: 75px;" class="text-center">DOB</th>
                    @elseif($showClass)
                        <th style="width: 55px;" class="text-center">Class</th>
                    @endif
                    <th style="width: 28%;">School</th>
                    <th style="width: 80px;" class="text-center">Attendance</th>
                </tr>
            </thead>
            <tbody>
                @php
                    $lastTeamKey = null;
                @endphp
                @foreach($rows as $i => $row)
                    @php
                        $teamName = $row['team_name'] ?? null;
                        $school = $row['school'] ?? '';
                        $groupId = $row['group_id'] ?? null;
                        $currentTeamKey = $groupId
                            ? 'g_'.$groupId
                            : ($teamName ? 't_'.$teamName.'_'.$school : null);
                    @endphp

                    @if($currentTeamKey && $currentTeamKey !== $lastTeamKey)
                        @php $lastTeamKey = $currentTeamKey; @endphp
                        <tr class="team-divider">
                            <td colspan="{{ $colspan }}">
                                <strong>TEAM: {{ strtoupper($teamName ?? 'Team Entry') }}</strong>
                                @if(!empty($school))
                                    &bull; <span style="color: #475569;">{{ strtoupper($school) }}</span>
                                @endif
                            </td>
                        </tr>
                    @endif

                    <tr>
                        <td class="text-center">{{ $serialOffset + $i + 1 }}</td>
                        <td class="photo-cell text-center">
                            @if(!empty($row['photo_url']))
                                <img src="{{ $row['photo_url'] }}" alt="">
                            @else
                                <span class="initials">{{ strtoupper(substr($row['name'] ?? '?', 0, 1)) }}</span>
                            @endif
                        </td>
                        <td class="text-center chest-no">{{ $row['reference'] ?? '—' }}</td>
                        <td>
                            <strong style="font-size: 9px;">{{ $row['name'] ?? '' }}</strong>
                            @if(!empty($row['team_name']))
                                <div><span class="team-tag">Team: {{ $row['team_name'] }}</span></div>
                            @endif
                        </td>
                        @if($showDob)
                            <td class="text-center" style="font-size: 8px; color: #475569;">{{ $row['dob'] ?? '—' }}</td>
                        @elseif($showClass)
                            <td class="text-center" style="font-size: 8px; color: #475569;">{{ $row['class'] ?? '—' }}</td>
                        @endif
                        <td class="school-name">{{ strtoupper($school) }}</td>
                        <td class="text-center"></td>
                    </tr>
                @endforeach
            </tbody>
        </table>
        @if(empty($isPreview) && ($isDomPdf ?? true))
        <div class="footer-container" style="margin-top: 7px;">
            <span class="footer-left">{{ $sahodaya->name ?? 'SAHODAYA' }} &bull; {{ $event->title }} &bull; Generated {{ now()->format('d M Y, h:i A') }}</span>
        </div>
        @endif
    </div>
@empty
    <p style="text-align: center; margin-top: 40px; color: #64748b;">No participants to display.</p>
@endforelse
</main>

</body>
</html>
