<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Mark Entry Report</title>
    <style>
        @page {
            margin: 25px 30px 25px 30px;
        }
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 10.5px;
            color: #1e293b;
            line-height: 1.4;
        }
        h2 {
            text-align: center;
            margin: 10px 0 4px;
            font-size: 16px;
            font-weight: bold;
            color: #0f172a;
            letter-spacing: -0.2px;
        }
        .meta {
            text-align: center;
            color: #64748b;
            margin-bottom: 4px;
            font-size: 10.5px;
        }
        .meta strong { color: #334155; }
        .for-whom {
            text-align: center;
            color: #334155;
            margin-bottom: 14px;
            font-size: 10.5px;
            font-style: italic;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 8px;
        }
        th {
            background-color: #f1f5f9;
            color: #334155;
            border: 1px solid #cbd5e1;
            padding: 5px 6px;
            font-size: 9.5px;
            font-weight: bold;
            text-transform: uppercase;
            letter-spacing: 0.2px;
        }
        td {
            border: 1px solid #e2e8f0;
            padding: 5px 6px;
            font-size: 10px;
            color: #334155;
            vertical-align: middle;
        }
        tr:nth-child(even) {
            background-color: #f8fafc;
        }
        .text-center { text-align: center; }
        .font-bold { font-weight: bold; }
        .footer {
            margin-top: 18px;
            text-align: right;
            color: #94a3b8;
            font-size: 9px;
        }
    </style>
</head>
<body>
    @include('partials.pdf-branding-header', ['orgName' => $orgName ?? ($sahodaya->name ?? 'Sahodaya'), 'logoSrc' => $logoSrc ?? null])

    <h2>{{ $event->title }} — Mark Entry Report</h2>
    <p class="meta">Generated by <strong>{{ $generatedBy }}</strong> on <strong>{{ $generatedAt }}</strong></p>
    @if($forWhom)
        <p class="for-whom">Prepared for: {{ $forWhom }}</p>
    @endif

    <table>
        <thead>
            <tr>
                <th style="width: 3%;">#</th>
                <th style="width: 10%;">Category</th>
                <th style="width: 17%;">Item</th>
                @if($showPhase)<th style="width: 8%;">Phase</th>@endif
                @if($showRegion)<th style="width: 8%;">Region</th>@endif
                <th style="width: 14%;">School</th>
                <th style="width: 14%;">Participant</th>
                <th style="width: 6%;" class="text-center">Chest</th>
                <th style="width: 6%;" class="text-center">Grade</th>
                <th style="width: 6%;" class="text-center">Rank</th>
                <th style="width: 6%;" class="text-center">Score</th>
            </tr>
        </thead>
        <tbody>
            @foreach($rows as $idx => $r)
            <tr>
                <td class="text-center" style="color: #94a3b8;">{{ $idx + 1 }}</td>
                <td>{{ $r['category_label'] }}</td>
                <td>
                    <strong>{{ $r['item_title'] }}</strong>
                    @if($r['item_code'])<span style="color: #94a3b8;"> ({{ $r['item_code'] }})</span>@endif
                </td>
                @if($showPhase)<td>{{ $r['phase_name'] ?? '—' }}</td>@endif
                @if($showRegion)<td>{{ $r['region_name'] ?? '—' }}</td>@endif
                <td>{{ strtoupper($r['school_name'] ?? '') }}</td>
                <td>{{ $r['participant'] }}</td>
                <td class="text-center font-bold">{{ $r['chest_no'] ?? '—' }}</td>
                <td class="text-center font-bold">{{ $r['grade'] ?? '—' }}</td>
                <td class="text-center">{{ $r['position'] ?? '—' }}</td>
                <td class="text-center">{{ $r['score'] ?? '—' }}</td>
            </tr>
            @endforeach
            @if(empty($rows))
            <tr><td colspan="11" class="text-center" style="padding: 20px; color: #94a3b8;">No registrations found.</td></tr>
            @endif
        </tbody>
    </table>

    <p class="footer">{{ count($rows) }} row(s) &middot; {{ $generatedAt }}</p>
</body>
</html>
