<?php

$commonContact = [
    'section_type' => 'contact',
    'variant' => 'side-by-side',
    'config' => ['eyebrow' => 'Contact', 'heading' => 'Connect with {{name}}'],
    'layout' => ['width' => 'standard', 'spacing' => 'spacious', 'surface' => 'muted', 'heading_alignment' => 'left'],
];

return [
    'network-directory' => [
        'name' => 'Network & Directory',
        'version' => '2.0.0',
        'purpose' => 'Help families and institutions discover member schools and membership services.',
        'audience' => 'Member schools, prospective members and the public',
        'character' => 'Civic, structured and data-forward',
        'accent' => 'Directory first',
        'design' => [
            'primary' => '#164E63', 'secondary' => '#0E7490', 'accent_color' => '#F59E0B',
            'display_font' => 'Manrope', 'body_font' => 'Inter', 'type_scale' => 'balanced',
            'density' => 'comfortable', 'surface' => 'bordered', 'corners' => 'soft',
            'buttons' => 'solid', 'images' => 'documentary', 'motion' => 'restrained',
            'navigation' => 'directory', 'footer' => 'directory',
        ],
        'widgets' => ['news_ticker' => false, 'admission_banner' => false, 'social_strip' => false],
        'sections' => [
            ['section_type' => 'hero', 'variant' => 'gradient-split', 'config' => ['eyebrow' => 'CBSE school network', 'heading' => '{{name}}', 'subheading' => 'Find schools, programmes and shared opportunities across {{region}}.', 'primary_label' => 'Find a member school', 'primary_url' => '#member-schools', 'secondary_label' => 'Membership services', 'secondary_url' => '/school-register'], 'layout' => ['width' => 'wide', 'spacing' => 'spacious', 'surface' => 'primary', 'heading_alignment' => 'left']],
            ['section_type' => 'statistics', 'variant' => 'counter-strip', 'config' => ['heading' => 'Our network at a glance'], 'layout' => ['width' => 'wide', 'spacing' => 'compact', 'surface' => 'canvas', 'heading_alignment' => 'center']],
            ['section_type' => 'member_schools', 'variant' => 'map-view', 'config' => ['eyebrow' => 'Directory', 'heading' => 'Find a member school', 'subheading' => 'Search by school name, district or location.'], 'layout' => ['width' => 'wide', 'spacing' => 'spacious', 'surface' => 'muted', 'heading_alignment' => 'left']],
            ['section_type' => 'about_sahodaya', 'variant' => 'with-stats', 'config' => ['eyebrow' => 'About the network', 'heading' => 'Stronger schools through collaboration'], 'layout' => ['width' => 'standard', 'spacing' => 'spacious', 'surface' => 'canvas', 'heading_alignment' => 'left']],
            ['section_type' => 'events_programs', 'variant' => 'upcoming-cards', 'config' => ['eyebrow' => 'What is next', 'heading' => 'Upcoming programmes'], 'layout' => ['width' => 'wide', 'spacing' => 'standard', 'surface' => 'canvas', 'heading_alignment' => 'left']],
            ['section_type' => 'office_bearers', 'variant' => 'modern-grid', 'config' => ['heading' => 'Network leadership'], 'layout' => ['width' => 'wide', 'spacing' => 'standard', 'surface' => 'muted', 'heading_alignment' => 'center']],
            ['section_type' => 'gallery', 'variant' => 'grid', 'config' => ['heading' => 'Sahodaya Event Gallery'], 'layout' => ['width' => 'wide', 'spacing' => 'spacious', 'surface' => 'dark', 'heading_alignment' => 'left']],
            ['section_type' => 'news_circulars', 'variant' => 'modern-feed', 'config' => ['heading' => 'Latest updates'], 'layout' => ['width' => 'standard', 'spacing' => 'standard', 'surface' => 'canvas', 'heading_alignment' => 'left']],
            $commonContact,
        ],
    ],

    'events-results-live' => [
        'name' => 'Events & Results Live',
        'version' => '2.0.0',
        'purpose' => 'Put registrations, deadlines, schedules and results within immediate reach.',
        'audience' => 'Coordinators, schools, parents and students',
        'character' => 'Energetic, status-led and concise',
        'accent' => 'Live operations',
        'design' => [
            'primary' => '#312E81', 'secondary' => '#7C3AED', 'accent_color' => '#F97316',
            'display_font' => 'Manrope', 'body_font' => 'Inter', 'type_scale' => 'compact',
            'density' => 'compact', 'surface' => 'elevated', 'corners' => 'rounded',
            'buttons' => 'solid', 'images' => 'vibrant', 'motion' => 'expressive',
            'navigation' => 'event', 'footer' => 'event',
        ],
        'widgets' => ['news_ticker' => true, 'admission_banner' => false, 'social_strip' => true],
        'sections' => [
            ['section_type' => 'hero', 'variant' => 'event-promo', 'config' => ['eyebrow' => 'Season hub', 'heading' => '{{name}} Events', 'subheading' => 'Registrations, schedules and results—kept in one live view.', 'primary_label' => 'View active programme', 'primary_url' => '#action-hub'], 'layout' => ['width' => 'full', 'spacing' => 'compact', 'surface' => 'dark', 'heading_alignment' => 'left']],
            ['section_type' => 'sahodaya_action_hub', 'variant' => 'seasonal', 'config' => ['heading' => 'What do you need today?', 'subheading' => 'Quick access changes with the current event stage.'], 'layout' => ['width' => 'wide', 'spacing' => 'compact', 'surface' => 'canvas', 'heading_alignment' => 'left']],
            ['section_type' => 'events_programs', 'variant' => 'upcoming-cards', 'config' => ['heading' => 'Upcoming events'], 'layout' => ['width' => 'wide', 'spacing' => 'standard', 'surface' => 'muted', 'heading_alignment' => 'left']],
            ['section_type' => 'kalotsav', 'variant' => 'registration-cta', 'config' => ['heading' => 'Kalotsav', 'description' => 'Registration and programme information for participating schools.'], 'layout' => ['width' => 'wide', 'spacing' => 'standard', 'surface' => 'primary', 'heading_alignment' => 'left']],
            ['section_type' => 'sports_meet', 'variant' => 'results-highlight', 'config' => ['heading' => 'Sports results'], 'layout' => ['width' => 'wide', 'spacing' => 'standard', 'surface' => 'canvas', 'heading_alignment' => 'left']],
            ['section_type' => 'news_circulars', 'variant' => 'grid', 'config' => ['heading' => 'Event notices'], 'layout' => ['width' => 'wide', 'spacing' => 'standard', 'surface' => 'muted', 'heading_alignment' => 'left']],
            ['section_type' => 'member_schools', 'variant' => 'modern-grid', 'config' => ['heading' => 'Participating schools'], 'layout' => ['width' => 'wide', 'spacing' => 'standard', 'surface' => 'canvas', 'heading_alignment' => 'center']],
            ['section_type' => 'contact', 'variant' => 'stacked', 'config' => ['heading' => 'Event help desk'], 'layout' => ['width' => 'narrow', 'spacing' => 'standard', 'surface' => 'dark', 'heading_alignment' => 'center']],
        ],
    ],

    'academic-resources' => [
        'name' => 'Academic Resources & Training',
        'version' => '2.0.0',
        'purpose' => 'Make circulars, resources, training and academic dates easy to discover.',
        'audience' => 'Principals, teachers and academic coordinators',
        'character' => 'Editorial, calm and text-first',
        'accent' => 'Knowledge centre',
        'design' => [
            'primary' => '#334155', 'secondary' => '#0F766E', 'accent_color' => '#CA8A04',
            'display_font' => 'Merriweather', 'body_font' => 'Inter', 'type_scale' => 'editorial',
            'density' => 'comfortable', 'surface' => 'flat', 'corners' => 'square',
            'buttons' => 'understated', 'images' => 'documentary', 'motion' => 'restrained',
            'navigation' => 'editorial', 'footer' => 'editorial',
        ],
        'widgets' => ['news_ticker' => false, 'admission_banner' => false, 'social_strip' => false],
        'sections' => [
            ['section_type' => 'hero', 'variant' => 'with-quicklinks', 'config' => ['eyebrow' => 'Academic network', 'heading' => 'Resources for better teaching and leadership', 'subheading' => '{{name}} brings circulars, training and academic dates together.', 'primary_label' => 'Search resources', 'primary_url' => '#resource-centre'], 'layout' => ['width' => 'wide', 'spacing' => 'spacious', 'surface' => 'canvas', 'heading_alignment' => 'left']],
            ['section_type' => 'resource_centre', 'variant' => 'search-grid', 'config' => ['heading' => 'Resource centre', 'subheading' => 'Search circulars and downloads by keyword, year or category.'], 'layout' => ['width' => 'wide', 'spacing' => 'standard', 'surface' => 'muted', 'heading_alignment' => 'left']],
            ['section_type' => 'academic_quicklinks', 'variant' => 'year-tabs', 'config' => ['heading' => 'Academic quick links'], 'layout' => ['width' => 'standard', 'spacing' => 'compact', 'surface' => 'canvas', 'heading_alignment' => 'left']],
            ['section_type' => 'events_programs', 'variant' => 'timeline', 'config' => ['heading' => 'Training and academic calendar'], 'layout' => ['width' => 'standard', 'spacing' => 'standard', 'surface' => 'canvas', 'heading_alignment' => 'left']],
            ['section_type' => 'programmes', 'variant' => 'service-grid', 'config' => ['heading' => 'Academic programmes'], 'layout' => ['width' => 'wide', 'spacing' => 'standard', 'surface' => 'muted', 'heading_alignment' => 'left']],
            ['section_type' => 'news_circulars', 'variant' => 'list', 'config' => ['heading' => 'Recent circulars'], 'layout' => ['width' => 'standard', 'spacing' => 'standard', 'surface' => 'canvas', 'heading_alignment' => 'left']],
            ['section_type' => 'about_sahodaya', 'variant' => 'single-column', 'config' => ['heading' => 'A community of practice'], 'layout' => ['width' => 'narrow', 'spacing' => 'spacious', 'surface' => 'canvas', 'heading_alignment' => 'left']],
            $commonContact,
        ],
    ],

    'confederation-governance' => [
        'name' => 'Confederation & Governance',
        'version' => '2.0.0',
        'purpose' => 'Present leadership, governance, official documents and statewide programmes clearly.',
        'audience' => 'Leaders, institutions, regulators, media and the public',
        'character' => 'Authoritative, spacious and formal',
        'accent' => 'Institutional trust',
        'design' => [
            'primary' => '#172554', 'secondary' => '#1E3A8A', 'accent_color' => '#C7A34A',
            'display_font' => 'Merriweather', 'body_font' => 'Inter', 'type_scale' => 'editorial',
            'density' => 'spacious', 'surface' => 'bordered', 'corners' => 'soft',
            'buttons' => 'bordered', 'images' => 'formal', 'motion' => 'restrained',
            'navigation' => 'institutional', 'footer' => 'institutional',
        ],
        'widgets' => ['news_ticker' => false, 'admission_banner' => false, 'social_strip' => false],
        'sections' => [
            ['section_type' => 'hero', 'variant' => 'full-bleed', 'config' => ['eyebrow' => 'Confederation', 'heading' => '{{name}}', 'subheading' => 'Shared leadership for CBSE schools across {{region}}.', 'primary_label' => 'Explore our governance', 'primary_url' => '#governance'], 'layout' => ['width' => 'full', 'spacing' => 'spacious', 'surface' => 'dark', 'heading_alignment' => 'left']],
            ['section_type' => 'about_sahodaya', 'variant' => 'with-timeline', 'config' => ['heading' => 'Our mandate and journey'], 'layout' => ['width' => 'standard', 'spacing' => 'spacious', 'surface' => 'canvas', 'heading_alignment' => 'left']],
            ['section_type' => 'statistics', 'variant' => 'horizontal-strip', 'config' => ['heading' => 'Collective reach'], 'layout' => ['width' => 'wide', 'spacing' => 'compact', 'surface' => 'primary', 'heading_alignment' => 'center']],
            ['section_type' => 'governance', 'variant' => 'structure', 'config' => ['eyebrow' => 'Governance', 'heading' => 'How we are organized'], 'layout' => ['width' => 'wide', 'spacing' => 'spacious', 'surface' => 'muted', 'heading_alignment' => 'left']],
            ['section_type' => 'member_schools', 'variant' => 'table-list', 'config' => ['heading' => 'Regional network'], 'layout' => ['width' => 'wide', 'spacing' => 'standard', 'surface' => 'canvas', 'heading_alignment' => 'left']],
            ['section_type' => 'office_bearers', 'variant' => 'photo-cards', 'config' => ['heading' => 'Office bearers'], 'layout' => ['width' => 'wide', 'spacing' => 'standard', 'surface' => 'muted', 'heading_alignment' => 'center']],
            ['section_type' => 'programmes', 'variant' => 'service-grid', 'config' => ['heading' => 'State programmes'], 'layout' => ['width' => 'wide', 'spacing' => 'standard', 'surface' => 'canvas', 'heading_alignment' => 'left']],
            ['section_type' => 'downloads_sahodaya', 'variant' => 'sahodaya-grid', 'config' => ['heading' => 'Official documents'], 'layout' => ['width' => 'standard', 'spacing' => 'standard', 'surface' => 'muted', 'heading_alignment' => 'left']],
            ['section_type' => 'news_circulars', 'variant' => 'modern-feed', 'config' => ['heading' => 'Official updates'], 'layout' => ['width' => 'standard', 'spacing' => 'standard', 'surface' => 'canvas', 'heading_alignment' => 'left']],
            ['section_type' => 'contact', 'variant' => 'stacked', 'config' => ['heading' => 'Secretariat'], 'layout' => ['width' => 'narrow', 'spacing' => 'spacious', 'surface' => 'dark', 'heading_alignment' => 'center']],
        ],
    ],
];
