<?php

namespace Tests\Unit\Support;

use App\Support\WordExport;
use Tests\TestCase;
use ZipArchive;

class WordExportTest extends TestCase
{
    public function test_download_produces_a_valid_docx_containing_the_table_data(): void
    {
        $response = WordExport::download(
            'winners',
            'Kalotsav 2026 — Top 3 Winners',
            [[
                'heading' => 'Classical Music Solo',
                'headers' => ['Rank', 'Student ID', 'Name'],
                'rows'    => [[1, '1111', 'Alpha']],
            ]],
            'Generated on 23 Sep 2026',
        );

        $this->assertSame(
            'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
            $response->headers->get('content-type'),
        );
        $this->assertStringContainsString('winners.docx', $response->headers->get('content-disposition'));

        $bytes = '';
        ob_start();
        $response->sendContent();
        $bytes = ob_get_clean();

        $tmp = tempnam(sys_get_temp_dir(), 'docx-test');
        file_put_contents($tmp, $bytes);

        $zip = new ZipArchive;
        $this->assertTrue($zip->open($tmp) === true, 'Generated bytes must be a valid zip/docx package.');

        $documentXml = $zip->getFromName('word/document.xml');
        $zip->close();
        unlink($tmp);

        $this->assertNotFalse($documentXml);
        $this->assertStringContainsString('Kalotsav 2026', $documentXml);
        $this->assertStringContainsString('Classical Music Solo', $documentXml);
        $this->assertStringContainsString('Student ID', $documentXml);
        $this->assertStringContainsString('1111', $documentXml);
        $this->assertStringContainsString('Alpha', $documentXml);
    }

    public function test_escapes_xml_special_characters_in_cell_content(): void
    {
        $response = WordExport::download(
            'winners',
            'Team A & B',
            [['headers' => ['Name'], 'rows' => [['<Alpha> & "Beta"']]]],
        );

        ob_start();
        $response->sendContent();
        $bytes = ob_get_clean();

        $tmp = tempnam(sys_get_temp_dir(), 'docx-test');
        file_put_contents($tmp, $bytes);

        $zip = new ZipArchive;
        $zip->open($tmp);
        $documentXml = $zip->getFromName('word/document.xml');
        $zip->close();
        unlink($tmp);

        $this->assertStringNotContainsString('<Alpha>', $documentXml);
        $this->assertStringContainsString('&lt;Alpha&gt;', $documentXml);
    }
}
